### ISSUE TITLE
One moment

### ISSUE THREAD

**Issue by Windslab** [NVlabs/stylegan2-ada#1]
Hi

> On Windows you need to use TensorFlow 1.14, as the standard 1.15 installation does not include necessary C++ headers.

Where I can find `TensorFlow 1.14` and do you have any guide how to setup? Thanks.

**Comment by branchnbound** [comment]
https://pypi.org/project/tensorflow/1.14.0/#files

Check that out. If you're also on Python 3.6, you can just use pip to install the specific tensorflow version you want
