### ISSUE TITLE
Continue training

### ISSUE THREAD

**Issue by vivekbharadhwajsa** [NVlabs/stylegan2-ada#106]
Hello, 

My training stopped after 7000 kimg and is it possible to continue training from the last kimg(where the training stopped) instead of starting the training again from 0 kimg? 

Thanks

**Comment by WuZongWei6** [comment]
I am facing the same problem.

**Comment by WuZongWei6** [comment]
> Hello,
> 
> My training stopped after 7000 kimg and is it possible to continue training from the last kimg(where the training stopped) instead of starting the training again from 0 kimg?
> 
> Thanks

Can you tell me how to solve it? Thanks!

**Comment by vivekbharadhwajsa** [comment]
> > Hello,
> > 
> > My training stopped after 7000 kimg and is it possible to continue training from the last kimg(where the training stopped) instead of starting the training again from 0 kimg?
> > 
> > Thanks
> 
> Can you tell me how to solve it? Thanks!
> 

During training command, use the "--resume" command and give the previous .pkl file as the argument

**Comment by WuZongWei6** [comment]
Thanks for your reply! I tried this method, but the kimg and tick change back to 0, and the augment also starts from zero. From the intermediate results, it seems that the network started a new training. If so, there seem to be no difference from training from scratch. Or am I misunderstanding at any step?

**Comment by WuZongWei6** [comment]
> > > Hello,
> > > My training stopped after 7000 kimg and is it possible to continue training from the last kimg(where the training stopped) instead of starting the training again from 0 kimg?
> > > Thanks
> > 
> > 
> > Can you tell me how to solve it? Thanks!
> 
> During training command, use the "--resume" command and give the previous .pkl file as the argument

Thanks for your reply! I tried this method, but the kimg and tick change back to 0, and the augment also starts from zero. From the intermediate results, it seems that the network started a new training. If so, there seem to be no difference from training from scratch. Or am I misunderstanding at any step?
