### ISSUE TITLE
how to setting the epochs ?

### ISSUE THREAD

**Issue by Adithia99** [NVlabs/stylegan2-ada#13]
im training with own dataset but dont know which one setting epoch. anybody can tell me which codes and line define epoch?

**Comment by woctezuma** [comment]
https://github.com/NVlabs/stylegan2-ada/blob/9b78595d6f17a0a2299093b1297b0dc6953ea0d1/train.py#L531-L536

**Comment by Adithia99** [comment]
KIMG? How? Default it 25000 right? But when i change to 5 still train forever

**Comment by woctezuma** [comment]
How many images do you have?

**Comment by Adithia99** [comment]
And by the way where the result? I dont see the result at all eventhough i was make outputdir and model too i dont have that

**Comment by Adithia99** [comment]
My ticks (epoch maybe) was 692 then i interupt it but got nothing

**Comment by Adithia99** [comment]
157 images

**Comment by Adithia99** [comment]
Oh okay, take forever its okay.. But i dont find the result and the pkl model bro
.. :(

**Comment by woctezuma** [comment]
> 157 images

Then 1 epoch corresponds to 0.157 kimg.

If you want to train for 1000 epochs, then set `--kimg=157`.

**Comment by Adithia99** [comment]
Okay thanks with the epoch, may i ask again about result and model too i cant find that

**Comment by woctezuma** [comment]
I don't know the solution.

You would need to open an other issue about that for greater visibility.
