### ISSUE TITLE
Can't see the GPU on Colab

### ISSUE THREAD

**Issue by baymak** [NVlabs/stylegan2-ada#16]
Hi, I try to run the code in Google Colab with GPU. However it fails to load the pertained network. It can't find the GPU. 

the code I ran is below as well as the error message. Thanks for the advice
!python generate.py --outdir=out --trunc=1 --seeds=0-35 --class=1 \
    --network='https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada/pretrained/cifar10.pkl'

  File "/content/stylegan2-ada/dnnlib/tflib/ops/fused_bias_act.py", line 72, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain, clamp=clamp)
  File "/content/stylegan2-ada/dnnlib/tflib/ops/fused_bias_act.py", line 132, in _fused_bias_act_cuda
    cuda_op = _get_plugin().fused_bias_act
  File "/content/stylegan2-ada/dnnlib/tflib/ops/fused_bias_act.py", line 18, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "/content/stylegan2-ada/dnnlib/tflib/custom_ops.py", line 139, in get_plugin
    compile_opts += f' --gpu-architecture={_get_cuda_gpu_arch_string()}'
  File "/content/stylegan2-ada/dnnlib/tflib/custom_ops.py", line 60, in _get_cuda_gpu_arch_string
    raise RuntimeError('No GPU devices found')
RuntimeError: No GPU devices found

**Comment by woctezuma** [comment]
You need to enable the GPU in your Colab session.

**Comment by baymak** [comment]
hi,
It is already enabled. I have double checked.

**Comment by seawee1** [comment]
I had the same error a few hours ago, on my local machine however. Had to uninstall the pip tensorflow-gpu package and reinstall it via conda. Also, did you switch your Colab instance to Tensorflow 1.x?

**Comment by baymak** [comment]
It seems this issue happens often and I have found the solution here: https://github.com/rolux/stylegan2encoder/issues/4

It  is not enough to install Tensorflow 1.x. It requires this comment:  !pip install tensorflow-gpu==1.14
now issue solved 😊

**Comment by mayankgrwl97** [comment]
> I had the same error a few hours ago on my local machine however. Uninstalling the pip tensorflow-gpu package and reinstalling it via conda solved the issue.
> Besides, did you switch your Colab instance to Tensorflow 1.x?

Works perfectly. Thanks!
