### ISSUE TITLE
Generate.py on Colab? Can generate image locally, but not on Colab

### ISSUE THREAD

**Issue by galabyca** [NVlabs/stylegan2-ada#17]
Hi,

I'm trying to generate images from a pretrained network on Colab, but didn't work. However, it went well locally.

Here was the command : 

!python generate.py --outdir=out --trunc=1 --seeds=0-35 --class=1 --network="https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada/pretrained/cifar10.pkl"

I also tried with the command given in the README file to generate curated MetFaces images. Again, this works well locally but not on Colab.

**Error:**
generate.py: error: unrecognized arguments: --outdir=out --trunc=1 --seeds=0-35 --class=1 --network=https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada/pretrained/cifar10.pkl

**Config**
Colab Pro
tensorflow_version 1.x (I also tried to force to version 1.14)
I double checked few times I was on a GPU, more precisely it's on the Tesla V100-SXM2

**Comment by woctezuma** [comment]
What if you remove the quotes around the url?

**Comment by b4nn3d** [comment]
I have the same issue.

**Comment by woctezuma** [comment]
Have you tried with a simpler command-line?

**Comment by woctezuma** [comment]
I cannot replicate your issue with the Metfaces network.

![minimal working example](https://i.imgur.com/yYOJzv5.png)

**Comment by woctezuma** [comment]
I cannot replicate your issue with the MetFaces network. [![Open In Colab][colab-badge]][colab-notebook]

**Comment by woctezuma** [comment]
I cannot replicate your issue with the MetFaces network. [![Open In Colab][colab-badge]][colab-notebook]

[colab-notebook]: <https://colab.research.google.com/github/woctezuma/stylegan2-ada/blob/minimal_working_example_for_generation/minimal_working_example_for_generation.ipynb>
[colab-badge]: <https://colab.research.google.com/assets/colab-badge.svg>

**Comment by b4nn3d** [comment]
yes, my mistake

**Comment by galabyca** [comment]
Thanks. I think the error was because of the way I linked the .pkl file (located on GDrive too) into the command. Works well now. Thanks!
