### ISSUE TITLE
how to fix the C++11 error

### ISSUE THREAD

**Issue by Johnson-yue** [NVlabs/stylegan2-ada#2]
Hi， I using tensorflow==1.14.0 ， CUDA 10.0 ， cuDNN 7.5.1   on Ubuntu16.04
but I meet a C++ bug

> C++ versions less than C++11 are not supported
> #error This file requires compiler and library support for the ISO c++ 2011 standard. This support must be enabled with the -std=C++11 or std=gun++11 compiler options

But I do not know where should I  add "-std=c++11 or -std=gun++11" or  Should I update my g++ version ??
How I fix it ?

**Comment by Johnson-yue** [comment]
when I add ‘--std=c++11’ in [_run_cmd()](https://github.com/NVlabs/stylegan2-ada/blob/ffa7883384c1e75297c7a1352fa392adf8a5c7d1/dnnlib/tflib/custom_ops.py#L159)
it failed

**Comment by ekolodin** [comment]
> when I add ‘--std=c++11’ in [_run_cmd()](https://github.com/NVlabs/stylegan2-ada/blob/ffa7883384c1e75297c7a1352fa392adf8a5c7d1/dnnlib/tflib/custom_ops.py#L159)
> it failed

Have a look here: https://stackoverflow.com/questions/59342888/tensorflow-error-this-file-requires-compiler-and-library-support-for-the-iso-c

**Comment by Johnson-yue** [comment]
thank you very much , it solve my problem!!!
