### ISSUE TITLE
how to create dataset with label

### ISSUE THREAD

**Issue by Johnson-yue** [NVlabs/stylegan2-ada#22]
If I want to finetune stylegan2-ada with conditional label how I prepare dataset ??

the readem had only for cifar10 dataset with conditional  but how to use for my own dataset??

what is the format of data ?

**Comment by tr1pzz** [comment]
[Here](https://storage.googleapis.com/public-assets-xander/Random/Create_Conditional_Dataset.ipynb) is my jupter notebook to create conditional datasets.

Note: this will not work out-of-the-box with StyleGAN's default dataloader, I'm using the tf_raw dataloader from [this repo](https://github.com/pbaylies/stylegan2) which you'll have to integrate (there's only a few lines you need to change) or alternatively change my jupyter notebook to dump default tfrecord files.

Main benefit of the raw_tfrecords is that they are about ~10 times smaller than the original tfrecs which is insanely helpful if you ask me...

**Comment by Johnson-yue** [comment]
@tr1pzz thank you , I will try it

**Comment by Johnson-yue** [comment]
@tr1pzz  Hi, my data is gray image ,so it  PIL.image.open(file) have a (256, 256)  and
I replace the original dataset_tool.py with your dataset_tool.py  and then use your jupyter notebook create a tfrecord successfully!

but when I try  finetuning , has a error about dataset.load_dataset() function

****/training/dataset.py", line 219, in parse_tfrecord_np
    data = ex.features.feature["data"].bytes_list.value[0]    # pylint : disable=no-member original
IndexError: list index (0) out of range

then I debug and found : 
 ` ex.features.feature["data"].bytes_list.value[0]  == None`
but
  ex.features.feature["img"].bytes_list.value[0]  is good data

I can not load the tfrecord, why ?

**Comment by tr1pzz** [comment]
Yeah, forgot about that, you also have to update a few minor things in dataset.py
You can take a look at the changes in [this repo](https://github.com/pbaylies/stylegan2).
Let me know if you get stuck, it should be an easy fix to figure out!

**Comment by Johnson-yue** [comment]
@tr1pzz  Hi ，I rewrite the data_tools.py  reference create_cifar10 dataset ，and not change the dataset.py， Thank you for your help

**Comment by ivanlen** [comment]
Hey @Johnson-yue , were you able to train the conditional version from a pretrained unconditional one?

**Comment by ivanlen** [comment]
Hi @aiXander , can you share again the notebook to generate a conditioned GAN from an uncoditioned?
cheers!

**Comment by jazz-ai** [comment]
> [Here](https://storage.googleapis.com/public-assets-xander/Random/Create_Conditional_Dataset.ipynb) is my jupter notebook to create conditional datasets.
> 
> Note: this will not work out-of-the-box with StyleGAN's default dataloader, I'm using a tf_raw format, simply replace the dataset_tool.py file with [this one](https://storage.googleapis.com/public-assets-xander/Random/dataset_tool.py) and it should work.
> 
> Main benefit of the raw_tfrecords is that they are about ~10 times smaller than the original tfrecs which is insanely helpful if you ask me...

Hi @aiXander, can you please repost the link to create conditional datasets.The above link is not working.

**Comment by Johnson-yue** [comment]
> Hey @Johnson-yue , were you able to train the conditional version from a pretrained unconditional one?

no,  because this not support!!   there are not pretrained conditional weight for finetuning
