### ISSUE TITLE
ffhq1024 fakes_init look bad

### ISSUE THREAD

**Issue by tr1pzz** [NVlabs/stylegan2-ada#3]
Upon running a straight, out-of-the-box train.py with --resume=ffhq1024, the "fakes_init.png" looks very weird:
https://storage.googleapis.com/public-assets-xander/fakes_init.jpg

**Comment by tr1pzz** [comment]
The problem disappears after finetuning for a very short amount of time though...
It's like the to_rgb layer is not properly initialized or something

**Comment by tr1pzz** [comment]
Ok, I think the reason is that the new network architecture, by default, only uses 2 mapping layers instead of 8, so not all the parameters are restored, hence the w+ space is essentially un-tuned when simply loading a pretrained ffhq.

It might make more sense to still use 8 mapping layers when restoring a SG2 checkpoint.

**Comment by woctezuma** [comment]
Yes. Thanks to this issue, I noticed as well. That is why I added to my fork (https://github.com/NVlabs/stylegan2-ada/pull/6) a command-line argument to override the mapping net depth.

**Comment by betterze** [comment]
@woctezuma @tr1pzz Thnak you for sharing this, I also find this problem. 

Do you have any insight about why they use mapping layers as 2 rather than 8? 2 layers give better performance?

Thank you in advance.

**Comment by woctezuma** [comment]
> Do you have any insight about why they use mapping layers as 2 rather than 8? 2 layers give better performance?

I don't know why they made the call to use a depth of 2 for the `auto` config. I guess that is because the authors noticed that it works better on CIFAR (as you can see on the table above, CIFAR+tuning uses a depth of 2 instead of 8), and thought that the datasets of other people might look more like CIFAR (more diverse and lower resolution).

**Comment by betterze** [comment]
@woctezuma Thank you for your detailed reply, I really appreciate it.
