### ISSUE TITLE
how to finetune ?

### ISSUE THREAD

**Issue by Johnson-yue** [NVlabs/stylegan2-ada#4]
Hi, If I have some data images (maybe 1k) how to finetune with it ?

**Comment by woctezuma** [comment]
Check unofficial repositories:
-   https://github.com/lucidrains/stylegan2-pytorch#low-amounts-of-training-data
-   https://github.com/rosinality/stylegan2-pytorch

**Comment by connor-john** [comment]
Its similar to stylegan2 if you want to do transfer learning edit the `training_loop.py` file in the `training` subfolder, namely the `resume_pkl` in the `training_loop` function. Then train on your custom dataset.

There are many resources/blog posts/etc about doing transfer learning with stylegan2 they should be able to help you more in depth.

**Comment by Johnson-yue** [comment]
@connor-john  thanks， I will try it , if I finish it will be close

**Comment by woctezuma** [comment]
Ctrl+F "transfer learning" in [the README](https://github.com/NVlabs/stylegan2-ada#training-new-networks).

```
## Training new networks

In its most basic form, training new networks boils down to:

```.bash
python train.py --outdir=~/training-runs --gpus=1 --data=~/datasets/custom
```

[...]

The training configuration can be further customized with additional arguments. Common examples:
* `--resume=ffhq1024 --snap=10` performs transfer learning from FFHQ trained at 1024x1024.
```

**Comment by Johnson-yue** [comment]
oh, yes, I see it and it worked, thank you
