### ISSUE TITLE
Is tf.nn.depthwise_conv2d_backprop_input equal to tf.nn.conv2d_transpose for implementing Upsample2D? 

### ISSUE THREAD

**Issue by yangyu12** [NVlabs/stylegan2-ada#46]
Hi,
   I am trying to adapt the codes to accommodate my project which is based on PyTorch. I have trouble with transferring the Upsample2D with a specific kernel (e.g. https://github.com/NVlabs/stylegan2-ada/blob/main/training/augment.py#L425) since pytorch does not have a corresponding API for `tf.nn.depthwise_conv2d_backprop_input`. I wonder if this operation is the same as `tf.nn.conv2d_transpose` so that I can safely replace it with `torch.nn.funtional.conv_transpose2d`. It would be very helpful if you can comment on it. Thanks a lot!

**Comment by taotaonice** [comment]
I am trying to adapt this augmentation script to pytorch, too. And I think the answer is yes.

**Comment by nurpax** [comment]
BTW, if you were not aware: we released an official stylegan2-ada pytorch version recently. See https://github.com/NVlabs/stylegan2-ada-pytorch

**Comment by taotaonice** [comment]
THX

**Comment by yangyu12** [comment]
@nurpax Thanks for the recommendation! I think this issue can be closed.
