### ISSUE TITLE
Upgrade code to tf 2.x


### ISSUE THREAD

**Issue by Borshig** [NVlabs/stylegan2-ada#52]
Can you upgrade code to tf 2.x. Look like old versions of tf is not avaliable to download

**Comment by nurpax** [comment]
Hi @Borshig, please see https://github.com/NVlabs/stylegan2-ada/issues/32#issuecomment-748225014 for our future plans.

**Comment by johndpope** [comment]
seems like things are going to migrate to pytorch instead - https://github.com/NVlabs/stylegan2-ada/issues/32

albeit - the upgrade path doesn't look too steep - I didn't give it my best shot 
https://www.tensorflow.org/guide/upgrade

but a naive step 1 - got a bunch of incompatibilities
https://gist.github.com/johndpope/6fda5f9a39375437dbfceb9728ba13a0
need to persevere and rally people behind a single fork to work from.
theres about 6 things broken  - someone please post gitfork - and we can focus efforts there.
