### ISSUE TITLE
metrics take forever to complete, no progress and some errors, and more Q's

### ISSUE THREAD

**Issue by kbuggenhout** [NVlabs/stylegan2-ada#56]
I am training my own model based on custom made images for an art project.
when I use stylegan2 I get metrics in about 15mins, I did see the warning that stylegan2-ada metrics can take a long time for the first metrics run, but its been running of 8 hours on a 48 core, V100 based machine, and hasnt produced any output. is there a debug function to see where its stuck? in linux I can only see that the python process is waiting on some output from the gpu.

training works as expected although quite slow, with auto giving me quite small batch sizes, my GPU has 32GB mem, and by default stylegan2-ada is only using 35% of gpu mem, by tweaking the config to 24G gpu complex, I get 54% of memory. guess I can tweak some more.

python calc_metrics.py --metrics=fid50k_full --network=./results/00001-romi1-auto1-kimg15000/network-snapshot-000160.pkl
....
....
Calculating real image statistics for fid50k_full...
2020-12-24 23:00:25.724829: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.

or is it not using my GPU at that moment, I ran it concurently with the training at some time, the training was hardly impacted, so the metrics run was not doing a lot.

**Comment by kbuggenhout** [comment]
small update, it definitly is using the GPU, but very limited

**Comment by kbuggenhout** [comment]
I switched to using an older ngc container using tf 1.14, which doesnt seem to slow down as the container using 1.15 ( the 20.10 ngc container). any progress on the pytorch implementation of stylegan2-ada? or a tf2 version?

**Comment by johndpope** [comment]
Tf2 compatibly mode / https://github.com/johndpope/stylegan2-ada/tree/digressions
