### ISSUE TITLE
Windows 10 Issue: CUDA 10.0 --> Microsoft Visual Studio 2017/2019 error

### ISSUE THREAD

**Issue by therealjjj77** [NVlabs/stylegan2-ada#59]
This is just a suggestion. You mentioned that Microsoft Visual Studio Community is needed. 
And also that CUDA 10.0 is needed. But CUDA 10.0 requires MVS 2017. So, you may want to specify that Microsoft Visual Studio 2017 is needed.

**Comment by therealjjj77** [comment]
So I haven't been able to get this working. Is CUDA 10.0 a strict requirement? Dry run works. I'm getting the following error on a normal run:

`RuntimeError: NVCC returned an error. See below for full command line and output log:

nvcc "C:\Users\Jerr\PycharmProjects\StyleGan\venv\lib\site-packages\tensorflow\python\_pywrap_tensorflow_internal.lib" --gpu-architecture=sm_75 --use_fast_math --disable-warnings --include-path "C:\Users\Jerr\PycharmProjects\StyleGan\v
env\lib\site-packages\tensorflow\include" --include-path "C:\Users\Jerr\PycharmProjects\StyleGan\venv\lib\site-packages\tensorflow\include\external\protobuf_archive\src" --include-path "C:\Users\Jerr\PycharmProjects\StyleGan\venv\lib\s
ite-packages\tensorflow\include\external\com_google_absl" --include-path "C:\Users\Jerr\PycharmProjects\StyleGan\venv\lib\site-packages\tensorflow\include\external\eigen_archive" --compiler-bindir "C:/Program Files (x86)/Microsoft Visu
al Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64" 2>&1 "C:\Users\Jerr\AppData\Roaming\JetBrains\PyCharmCE2020.2\scratches\stylegan2-ada-main\dnnlib\tflib\ops\fused_bias_act.cu" --shared -o "C:\Users\Jerr\AppData\Local
\Temp\tmp_x5fai3l\fused_bias_act_tmp.dll" --keep --keep-dir "C:\Users\Jerr\AppData\Local\Temp\tmp_x5fai3l"

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\crt/host_config.h(143): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2013 and 2017 (inclusive) are supported!
_pywrap_tensorflow_internal.lib
fused_bias_act.cu
`

I've got Tensorflow-GPU 1.14, Python 3.6, 
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130
`
Using CuDNN 7.5. I have the path pointing to the VS2019 bat file as mentioned in the instructions.

**Comment by therealjjj77** [comment]
I fixed the issue by opening the CUDA/v10.0/include/crt/host_config.h and changing line 141 to

`#if _MSC_VER < 1700 || _MSC_VER >= 2000`

But I would recommend not installing the latest version of Microsoft Visual Studio. Recommend install the first release of Microsoft Visual Studio 2019. That will still be covered by the original file.

**Comment by ebrarsahin** [comment]
How can i change host_config.h file ?? Not allow the saving file..
