### ISSUE TITLE
Learning the code question

### ISSUE THREAD

**Issue by foobar8675** [NVlabs/stylegan2-ada#67]
I was hoping for some advice. I would like to learn this code but am new to Tensorflow. When looking at Tensorflow tutorials online, they all refer to 2.0. So my question, is would the 2.0 documentation good enough or are the changes so significant, I should really be looking for a 1.15 tutorial?

**Comment by nurpax** [comment]
If you're not in a hurry, instead of learning TensorFlow 1.x, I'd recommend reading about PyTorch given that we're porting StyleGAN2 ADA to PyTorch: https://github.com/NVlabs/stylegan2-ada/issues/32#issuecomment-748225014

**Comment by foobar8675** [comment]
awesome! thanks!
