### ISSUE TITLE
crazy slowdown in processing time in stylegan2-ada/train.py --resume on Colab

### ISSUE THREAD

**Issue by MoemaMike** [NVlabs/stylegan2-ada#88]
I understand this is probably not a stylegan2-ada code issue but no idea where else to turn. Trying to train my first custom model. Dataset 2500 1024x1024 images. Colab Pro Tesla P100-PCIE plenty of RAM, plenty of disk.
Ran successfully for 2 days with one restart after colab disconnect. to restart i used resume to pick up where i left off with last .pkl file from previous run. For those 2 runs the I was getting timings consistently around 
sec/tick 698.6   sec/kimg 174.65 maintenance 774.5 
see attached log-goodResume.txt

After second Colab disconnect (3rd day) i repeated the same --resume pattern with last created .pkl
This time and 2 subsequent attempts the performance is ridiculously slow from the outset
sec/tick 1941.7  sec/kimg 485.43  maintenance 2219.6 
see attached log-badResume.txt

[log-goodResume.txt](https://github.com/NVlabs/stylegan2-ada/files/6192523/log-goodResume.txt)
[log-badResume.txt](https://github.com/NVlabs/stylegan2-ada/files/6192524/log-badResume.txt)

The only procedural change i made between the first --resume which worked well and the later resumes which are unworkably slow is that in the latter runs i moved and renamed the pkl file that i want to resume to be.. more convenient located and named.  i.e i moved network-snapshot-000320.pkl up a folder and renamed it latest.pkl so that my subsequent resumes would not require changing my train.py resume clause in the  command.. just a convenience pattern which i assume should have no bearing on the slowdown

Any advice on how to resovlve this would be appreciated. i am kind of dead in the water now.

**Comment by nurpax** [comment]
Hi!  Not saying that this is guaranteed to fix your problem, but if you plan on doing more work with stylegan2-ada, I'd absolutely recommend switching over to the official PyTorch reimplementation of StyleGAN2-ADA: https://github.com/NVlabs/stylegan2-ada-pytorch

**Comment by MoemaMike** [comment]
thanks for fast reply. The issue is Colab GPU. New to Colab Pro and thought they were giving me the same GPU but turns out the good runs were on Tesla V100 and the poor runs were on Tesla P100. Not something that is visible in the logs.

Also, i did try to start off with stylegan2-ada-pytorch ... that was my objective but at least last week there was an unresolved issue on Colab. I will try again and see if the issue has been resolved. 

BTW tfrecords are opaque but stylegan2-ada-pytorch uses png files yes? I noticed when using the  stylegan2-ada-pytorch/dataset_tool.py that it was transforming my 300 DPI images to 72 DPI and there seemed to be no way to control that. as i am doing this as a digital artist i would prefer the higher DPI but am i correct to assume you guys are keeping DPI low to increase processing speed?

What is best forum to discuss stylegan2-ada techniques and issues that are not bugs?

great work btw

**Comment by nurpax** [comment]
Yes, the pytorch version uses just PNG files.

The dataset_tool.py only cares about images width/height pixel resolution, so if you give it 1024x1024 images, it should keep them at that resolution unless you explicitly tell it to resize with `--width`/`--height` options.

On Colab, remember to at least try to install "ninja" with `!pip install ninja`.  The error messages for build errors can be hard to diagnose, and forgetting to install ninja is common.  I think a bunch of folks have managed to get it working.

Sorry, I'm not sure what's the best forum for free discussion.  We don't host any forums ourselves and don't really have any "official endorsements".  I'd suggest searching on Twitter and Reddit and see what you can find.

**Comment by MoemaMike** [comment]
thank you. you may close

**Comment by MoemaMike** [comment]
thank you.
